### ISSUE TITLE
Question: Possible to use ActivityLog for custom events

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/activity-log#18]
This is  a **question**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

I use a custom event `InvoiceSent` in my code.
I dispatch it the following way - after a button click: `InvoiceSent::dispatch($invoice);`
The Event calls a notification and sends a invoice to a customer.

It would be nice to use your activity log to store and show when which invoice was sent to a customer.
Your activity-log looks perfect for that use case.

I played a little bit around today but I could not manage to get it working.

What I did:
- I extended your Enums
- I created a new Observer
- I added the needed things to my event

My question is (this part is not clear to me):
- How can I create a connection between the event and the Logger so that a log entry is written after the Event is triggered?

It would be nice if you can help me to get back on track.

Thx.

**Comment by raftx24** [comment]
Hi @mauthi .
I guess you need to implement an Event for it (something like [Created](https://github.com/laravel-enso/activity-log/blob/master/src/Observers/Created.php)), after that, you can store the activity log in this way `(new Factory(new InvoiceSent($invoice)))->create();`

**Comment by raftx24** [comment]
Hi @mauthi .
I guess you need to implement an Event for it (something like [Created](https://github.com/laravel-enso/activity-log/blob/master/src/Observers/Created.php)), after that, you can store the activity log in this way `(new Factory(new InvoiceSent($invoice)))->create();`

**Comment by mauthi** [comment]
Hi,

thx for your help. Now it works.

And, my fault - it's documented pretty well in https://docs.laravel-enso.com/backend/activity-log.html#creating-custom-events.
