### ISSUE TITLE
Activity log is not working

### ISSUE THREAD

**Issue by heyner29** [laravel-enso/activity-log#9]
This is  a **bug**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

Since the last update it no longer works.
A few days ago I made [a comment](https://github.com/enso-ui/ui/commit/1c7569432f3d05aa4068b08269c416fb976d9bc1#comments) where I think the problem is.

### Steps to Reproduce
Visit the [demo page](https://www.laravel-enso.com/activityLog).

### Expected behavior
Show activity logs

### Actual behavior
It manages to recover the records from the api, but fails to render them.

**Comment by aocneanu** [comment]
This package needs complete refactoring, along with the calendar. We'll do that soon.
